jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: ERROR


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/art_admin
    username: root
    password: 123456
  threads:
    virtual:
      enabled: true
  mvc:
    async:
      request-timeout: 120m
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

upload:
  picture-recycle: D:\warehouse\Recycle\pictureRecycle\  #图片回收
  audit-area: D:\warehouse\unstructuredData\video\auditArea\ #视频审核分类
  work-area: D:\warehouse\unstructuredData\video\workArea\  #视频资源等候区
  video-recycle: D:\warehouse\Recycle\videoRecycle\   #不通过的视频
  pass-area: D:\warehouse\unstructuredData\video\passArea\  #通过的视频
  picture-dir: D:\warehouse\unstructuredData\picture\   #图片存放

logging:
  level:
    root: warn
register:
  token: $2a$10$oAviUU2aAhrHEF
